### ISSUE TITLE
Tutorial Level

### ISSUE THREAD

**Issue by bflanagin** [VagueEntertainment/untitled_space_frisbee_game#6]
- [x] Requires [Tutorial option on main menu](https://github.com/VagueEntertainment/untitled_space_frisbee_game/issues/8)
- [x] Requires [Hanger Scene](https://github.com/VagueEntertainment/untitled_space_frisbee_game/issues/7)
- [x] Requires [Player Setup](https://github.com/VagueEntertainment/untitled_space_frisbee_game/issues/9)

Need a place to learn how to fly and control the disc. 

This also works as a place to fine tune aspects of the controls.

**Comment by bflanagin** [comment]
Current implementation is lacking a lot. Will need to focus on other aspects of the game and get back to this when I have a better Idea of what I'm hoping / looking for.

**Comment by bflanagin** [comment]
- [ ] Drones: 
    - [ ] Simple AI
- [ ] Player logic 
    - [ ] Call out (to be included in targeting)
    - [ ] Respond to Call out (Only all targeting of those that have called out)
- [ ] Goal: What should it look like
    - [ ] Score increase
    - [ ] Reset for next round?
